#!/usr/bin/sh
# @author nate zhou
# @since 2025
# Redirect status info to dvtmblocks.fifo for dvtm.
# Icons are disabled for better tty rendering.

#set -x
# INI
FIFO=${XDG_RUNTIME_DIR}/dvtmblocks.fifo
[ -p "$FIFO" ] || rm "$FIFO"
[ -e "$FIFO" ] || mkfifo "$FIFO"

printf "$$" > "${XDG_RUNTIME_DIR}/dvtmblocks.pid"
sec=0

# MODULES
update_time () {
	time=$(date '+%H:%M')
}

update_battery () {
    local POWER="/sys/class/power_supply"
    local status="$(cat $POWER/BAT?/status)"
    local level="$(cat $POWER/BAT?/capacity)"
    case "$status" in
        "Discharging")
            icon="FUL"
            level="${level}%"
            ;;
        "Not charging")
            icon="BAT" level="${level}%"
            ;;
        "Charging")
            icon="CHR" level="${level}%"
            ;;
    esac
    ls ${POWER}/BAT? > /dev/null || icon="CHR"
    battery="${icon} ${level}"
}

# For audio & brightness modules, save to XDG_CACHE_HOME for reboot consistency
update_volume() {
    local level=$(cat "${XDG_CACHE_HOME}/audio-@DEFAULT_AUDIO_SINK@.level")
    local muted=$(cat "${XDG_CACHE_HOME}/audio-@DEFAULT_AUDIO_SINK@.muted")
    [ -z "$muted" ] && icon="VOL" || icon="MUT"
    [ -z "$level" ] || level="${level}%"
    volume="${icon} ${level}"
}

update_brightness() {
    local icon="BRI"
    local level="$(cat ${XDG_CACHE_HOME}/brightness.level)"
    [ -z "$level" ] || level="${level}%"
    brightness="${icon} ${level}"
}

update_cpu() {
    local usage="$(mpstat --dec=0 | awk 'NR==4 {print 100 - $NF}')"
    local icon="CPU"
    [ -z "$usage" ] || usage="${usage}%"
    cpu="${icon} ${usage}"
}

update_memory() {
    local usage="$(command free | awk '/Mem:/ {printf "%.0f\n", $3/$2 * 100}')"
    local icon="MEM"
    [ -z "$usage" ] || usage="${usage}%"
    memory="${icon} ${usage}"
}

update_ttylogin() {
    local count="$(w -h | wc -l )"
    local icon="USR"
    ttylogin="${icon} ${count}"
}


display() {
    local space=" "         # ` `(U+2009) is the Thin Space
    local separator="|"
    printf "%s" "${ttylogin}${separator}${memory}${separator}${cpu}${separator}${brightness}${separator}${volume}${separator}${battery}${separator}${time}" > "$FIFO"
}

while true
do
	sleep 1 & wait && {
		# to update item ever n seconds with a offset of m
		## [ $((sec % n)) -eq m ] && udpate_item
		[ $((sec % 10 )) -eq 0 ] && update_time	# update time every 5 seconds
		[ $((sec % 30)) -eq 0 ] && update_battery
		[ $((sec % 10)) -eq 0 ] && update_brightness
		[ $((sec % 10)) -eq 0 ] && update_volume
		[ $((sec % 10)) -eq 0 ] && update_cpu
		[ $((sec % 10)) -eq 0 ] && update_memory
		[ $((sec % 60)) -eq 0 ] && update_ttylogin

		# how often the display updates ( 5 seconds )
		[ $((sec % 5 )) -eq 0 ] && display

		sec=$((sec + 1))
	}
done
